services:
  # 7 days to die server
  7daystodie_server:
    image: vinanrra/7dtd-server:latest
    container_name: 7daystodie_server
    profiles:
      - 7daystodie_server
    restart: on-failure:5
    depends_on:
      main_7daystodie:
        condition: service_completed_successfully
    ports:
      - "26900:26900"
      - "26901:26901"
      - "26902:26902"
#      - "8080:8080" # WEBADMIN
#      - "8081:8081" # TELNET
#      - "8082:8082" # WEBSERVER
    volumes:
      - 7daystodie_server_save:/home/sdtdserver/.local/share/7DaysToDie     # 7 Days To Die world saves
      - 7daystodie_server_config_lgsm:/home/sdtdserver/lgsm/config-lgsm/sdtdserver  # LGSM config folder
      - 7daystodie_server_file:/home/sdtdserver/serverfiles                # Optional - serverfiles folder
      - 7daystodie_server_log:/home/sdtdserver/log   
    networks:
      - 7daystodie_network
    env_file:
      - ./7daystodie/env/7daystodie.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G

  7daystodie_backup:
    image: mazzolino/restic:latest
    container_name: 7daystodie_backup
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - UID=${PUID:-1000}
      - GID=${PGID:-1000}
    profiles:
      - 7daystodie_backup
#    depends_on:
#      - 7daystodie_server
    restart: on-failure:5
    env_file:
      - ./7daystodie/env/7daystodie_backup.env
    volumes:
      - 7daystodie_backup:/mnt/restic
      - 7daystodie_backup_cache:/.cache
      - 7daystodie_server_save:/data/.local/share/7DaysToDie:ro
      - 7daystodie_server_config_lgsm:/data/lgsm/config-lgsm/sdtdserver:ro
      - 7daystodie_server_file:/data/serverfiles:ro
      - 7daystodie_server_log:/data/log:ro
    networks:
      - 7daystodie_network
    security_opt:
      - no-new-privileges:true

volumes:
  7daystodie_backup:
    name: 7daystodie_backup
  7daystodie_backup_cache:
    name: 7daystodie_backup_cache
  7daystodie_server_save:
    name: 7daystodie_server_save
  7daystodie_server_config_lgsm:
    name: 7daystodie_server_config_lgsm
  7daystodie_server_file:
    name: 7daystodie_server_file
  7daystodie_server_log:
    name: 7daystodie_server_log
