services:
  main_7daystodie:
    container_name: main_7daystodie
    image: alpine:latest
    profiles:
      - main_7daystodie
    volumes:
      - 7daystodie_openssh_config:/7daystodie_server/openssh_config:rw
      - 7daystodie_server_save:/7daystodie_server/save:rw
      - 7daystodie_server_config_lgsm:/7daystodie_server/config_lgsm:rw
      - 7daystodie_server_file:/7daystodie_server/file:rw
      - 7daystodie_server_log:/7daystodie_server/log:rw
      - 7daystodie_backup:/7daystodie_server/backup:rw
      - 7daystodie_backup_cache:/7daystodie_server/backup_cache:rw
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
    # Fix root permissions on mounted volumes
    command: chown -R ${PUID:-1000}:${PGID:-1000} /7daystodie_server

volumes:
  7daystodie_openssh_config:
    name: 7daystodie_openssh_config
  7daystodie_backup:
    name: 7daystodie_backup
  7daystodie_backup_cache:
    name: 7daystodie_backup_cache
  7daystodie_server_save:
    name: 7daystodie_server_save
  7daystodie_server_config_lgsm:
    name: 7daystodie_server_config_lgsm
  7daystodie_server_file:
    name: 7daystodie_server_file
  7daystodie_server_log:
    name: 7daystodie_server_log

networks:
  7daystodie_network:
    driver: bridge
    name: 7daystodie_network