version: "3.8"

services:
  mc-proxy:
    image: itzg/bungeecord:latest
    container_name: minecraft-proxy-server
    profiles:
      - mc-proxy
    restart: on-failure:3
    env_file:
      - env/proxy.env
    environment:
      INIT_MEMORY: "512M"
      MAX_MEMORY: "2048M"
    ports:
      #       Server Minecraft port
      - "25565:25577"
      #       Server Minecraft Bedrock port (GeyserMC)
      #- "19132:19132/udp"
      #       Rcon port
      #- "25576:25575"
      #       Plan port
      # - "8806:8804"
    volumes:
      - ./mc-proxy:/server
    networks:
      - app-network


  7dtd-server:
    image: vinanrra/7dtd-server:latest
    container_name: 7dtd-server
    profiles:
      - 7dtd-server
    restart: on-failure:3
    ports:
      - "26900:26900"
      - "26901:26901"
      - "26902:26902"
      - "8080:8080" # WEBADMIN
      - "8081:8081" # TELNET
      - "8082:8082" # WEBSERVER
    env_file:
      - env/server.env
    volumes:
      - ./server-data:/home/sdtdserver/.local/share/7DaysToDie/     # 7 Days To Die world saves
      - ./config-lgsm:/home/sdtdserver/lgsm/config-lgsm/sdtdserver # LGSM config folder
      - ./server-files:/home/sdtdserver/serverfiles/                # Optional - serverfiles folder
      - ./server-log:/home/sdtdserver/log/                
      - ./server-backup:/home/sdtdserver/lgsm/backup/ 
    networks:
      - app-network
      
volumes:
  server-data: 
    name: server-data
  config-lgsm:
    name: config-lgsm
  server-files:
    name: server-files
  server-log:
    name: server-log
  server-backup:
    name: server-backup

networks:
  app-network:
    driver: bridge
    name: app-network
