include:
# 7 days to die server
  - 7daystodie-server/7daystodie/docker-compose.7daystodie.yml
# OpenSSH server
  - 7daystodie-server/openssh/docker-compose.openssh.yml
# Backup server
  - 7daystodie-server/backup/docker-compose.backup.yml
