services:
  7dtd-server:
    image: vinanrra/7dtd-server:latest
    container_name: 7dtd-server
    profiles:
      - 7dtd-server
    restart: on-failure:3
    ports:
      - "26900:26900"
      - "26901:26901"
      - "26902:26902"
      - "8080:8080" # WEBADMIN
      - "8081:8081" # TELNET
      - "8082:8082" # WEBSERVER
    env_file:
      - env/server.env
    volumes:
      - ./server-data:/home/sdtdserver/.local/share/7DaysToDie/     # 7 Days To Die world saves
      - ./config-lgsm:/home/sdtdserver/lgsm/config-lgsm/sdtdserver  # LGSM config folder
      - ./server-files:/home/sdtdserver/serverfiles/                # Optional - serverfiles folder
      - ./server-log:/home/sdtdserver/log/                
#      - ./server-backup:/home/sdtdserver/lgsm/backup/ 
    networks:
      - app-network

  7dtd_backup:
    image: mazzolino/restic:latest
    container_name: 7dtd_backup
    profiles:
      - 7dtd-server
    depends_on:
      - 7dtd-server
    restart: on-failure:5
    env_file:
      - env/backup.env
    volumes:
      - ./server-backup:/mnt/restic
      - ./server-data:/data/server-data:ro
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
      
volumes:
  server-data: 
    name: server-data
  config-lgsm:
    name: config-lgsm
  server-files:
    name: server-files
  server-log:
    name: server-log
  server-backup:
    name: server-backup

networks:
  app-network:
    driver: bridge
    name: app-network
